apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-serverless
spec:
  destination:
    name: ''
    namespace: openshift-serverless
    server: 'https://kubernetes.default.svc'
  source:
    path: openshift-serverless
    repoURL: 'https://github.com/r3dact3d/OpenShift-Serverless'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
