apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-delivery
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: openshift/hello-openshift
        env:
        - name: RESPONSE
          value: "Hello Peoples!"
