apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-delivery
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        autoscaling.knative.dev/target: "1"
      name: hello-peeps
    spec:
      containerConcurrency: 100
      containers:
      - image: openshift/hello-openshift
        env:
        - name: RESPONSE
          value: "Hello Peoples!"

