---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    olm.providedAPIs: KnativeEventing.v1alpha1.operator.knative.dev,KnativeKafka.v1alpha1.operator.serverless.openshift.io,KnativeServing.v1alpha1.operator.knative.dev
  name: openshift-serverless-2pj2j
  namespace: openshift-serverless
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-serverless
  labels:
    operators.coreos.com/serverless-operator.openshift-serverless: ''
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: '4.7'
  installPlanApproval: Automatic
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: serverless-operator.v1.13.0

---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  controller-custom-certs:    #If registry uses self-signed cert 
    name: config-service-ca 
    type: ConfigMap           #Secret or ConfigMap, needs to be in this project
  high-availability:
    replicas: 1               #HA disabled; >1 to enable HA
    
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing    
  annotations:
    argocd.argoproj.io/sync-wave: "1"
